server:
  port: 8080
  servlet:
    context-path: /miniproject

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/miniproject"
    username: root
    password: hunghet1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  # Thymeleaf Configuration
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html


